### ISSUE TITLE
How can one best contribute to this library?

### ISSUE THREAD

**Issue by nlbuescher** [Dominaezzz/kgl#16]
Is there a todo list for a stable release that one could get involved in?

**Comment by Dominaezzz** [comment]
The TODO list is short, which is pretty much the open issues.

The bulk of the work that needs to be done is code generation. The code for generating multi-platform Kotlin is still fairly painful (especially for `kgl-vulkan`), I started from scratch 4 times before publishing and I'm still not very happy with it. I wouldn't recommend going in there to add more features, as it is a tangle of edge cases. Although if you have suggestions to simplify it, I'll happily hear them.
The code for `kgl-opengl` is fairly simple in comparison right now, since it's native only, that would be a good place to start. Generating more than just core functions is on the TODO list.

A stable release won't happen until Kotlin/Native is stable. Also, until recently, I haven't gotten a lot of feedback from users to know what works and what doesn't. If the APIs are usable and adequate as they ought to be.

Another good way to contribute would be to write up more samples. I have very few right now, due to lack of a multi-platform math library.

The last thing I can think of right now, is opening issues. A fair bit a design work needs to be done and to do that, discussions about it need to happen, no better place for that than an issue.

**Comment by nlbuescher** [comment]
Awesome. Makes a lot of sense. I've been following a C++ tutorial for a game engine for a while, and got to the end of the playlist. I switched the project over to use the KGL libraries in a test branch (awesome work so far), but I've been using mostly the opengl bindings (which as you mentioned are all native, so no surprise they work perfectly). I'm also using basically everything except vulkan. STB currently has an issue which prevents me from using it, so I'll open an issue for that.

One thing I also ran into is the math library lack, so I wrote my own matrix classes based conceptually on glm. That might be a good place to start: a kgl-math library.

I don't have a lot of experience using graphics libraries yet, but writing samples would give me an opportunity to gather some.
